class UiValues {
  static const Map<String, double> _values = {
    'api.timeout_seconds': 30,
    'splash.duration_ms': 3000,
    'splash.logo_size_factor': 0.34,
    'splash.title_size_factor': 0.055,
    'splash.tagline_size_factor': 0.032,
    'splash.loading_text_size_factor': 0.028,
    'splash.version_text_size_factor': 0.023,
    'splash.title_gap_factor': 0.025,
    'splash.tagline_gap_factor': 0.008,
    'splash.loading_gap_factor': 0.018,
    'splash.bottom_gap_factor': 0.025,
    'splash.progress_horizontal_factor': 0.16,
    'splash.progress_height': 5,
    'splash.progress_radius': 99,
    'splash.progress_background_alpha': 0.22,
    'splash.version_alpha': 0.65,
    'splash.top_spacer_flex': 3,
    'splash.middle_spacer_flex': 2,
    'home.header.icon_size': 34,
    'home.header.button_size': 56,
    'home.header.button_border_width': 1.5,
    'home.header.button_radius': 28,
    'home.header.horizontal_padding_factor': 0.055,
    'home.header.top_padding_factor': 0.012,
    'home.hero.logo_size_factor': 0.23,
    'home.hero.title_size_factor': 0.064,
    'home.hero.title_weight': 800,
    'home.hero.subtitle_size_factor': 0.034,
    'home.hero.tagline_size_factor': 0.028,
    'home.hero.logo_gap_factor': 0.005,
    'home.hero.title_gap_factor': 0.008,
    'home.hero.tagline_gap_factor': 0.014,
    'home.input.height_factor': 0.085,
    'home.input.horizontal_margin_factor': 0.052,
    'home.input.radius': 26,
    'home.input.border_width': 1.5,
    'home.input.icon_size': 32,
    'home.input.text_size_factor': 0.031,
    'home.input.content_padding_factor': 0.035,
    'home.input.background_alpha_dark': 0.42,
    'home.input.background_alpha_light': 0.62,
    'home.download_button.height_factor': 0.064,
    'home.download_button.horizontal_margin_factor': 0.052,
    'home.download_button.radius': 26,
    'home.download_button.icon_size': 34,
    'home.download_button.text_size_factor': 0.04,
    'home.download_button.gap_factor': 0.017,
    'home.platforms.card_height_factor': 0.082,
    'home.platforms.horizontal_gap_factor': 0.032,
    'home.platforms.horizontal_margin_factor': 0.052,
    'home.platforms.radius': 24,
    'home.platforms.border_width': 1.2,
    'home.platforms.logo_size_factor': 0.095,
    'home.platforms.label_size_factor': 0.028,
    'home.platforms.label_gap_factor': 0.01,
    'home.platforms.top_gap_factor': 0.018,
    'home.platforms.logo_inner_padding_factor': 0.12,
    'home.recent_downloads.top_gap_factor': 0.022,
    'home.recent_downloads.title_size_factor': 0.035,
    'home.recent_downloads.see_all_size_factor': 0.028,
    'home.recent_downloads.item_height_factor': 0.09,
    'home.recent_downloads.item_radius': 22,
    'home.recent_downloads.item_gap_factor': 0.012,
    'home.recent_downloads.thumbnail_width_factor': 0.18,
    'home.recent_downloads.thumbnail_radius': 15,
    'home.recent_downloads.content_margin_factor': 0.052,
    'home.bottom_navigation.height_factor': 0.102,
    'home.bottom_navigation.margin_factor': 0.006,
    'home.bottom_navigation.radius': 32,
    'home.bottom_navigation.border_width': 1.2,
    'home.bottom_navigation.label_size_factor': 0.027,
    'home.bottom_navigation.icon_size': 29,
    'home.bottom_navigation.active_indicator_width_factor': 0.055,
    'home.bottom_navigation.active_indicator_height': 4,
    'home.bottom_navigation.active_indicator_radius': 99,
    'home.bottom_navigation.active_indicator_gap': 4,
    'home.bottom_navigation.surface_alpha': 0.78,
    'home.platforms.surface_alpha': 0.55,
    'home.content_spacing_factor': 0.012,
    'home.scroll_bottom_padding_factor': 0.13,
  };

  static double value(String key) {
    final value = _values[key];
    if (value == null) {
      throw FormatException('Missing UI value: $key');
    }
    return value;
  }

  static int integer(String key) => value(key).round();
}
